### ISSUE TITLE
Pinging the maintainer(s)

### ISSUE THREAD

**Issue by Athanasius** [felixlinker/ed-forge#36]
I'd already tried pinging @felixlinker on the EDCD Discord.

EDCD Council is wondering if it would help to actively try finding an additional maintainer for this project.  To aid in that it would be good to know any pertinent information about the current state of both this project and that nascent "write a library that has better code quality/API" project.

Users have been reporting a few newer items, and some bugs:  e.g. https://discord.com/channels/164411426939600896/164411501166198784/1000063397854990366 https://discord.com/channels/164411426939600896/164411501166198784/1016084611622780989

**Comment by Athanasius** [comment]
And now I realise that I clicked the *first* github link in the EDCD channel title, not the one for coriolis, but you know what I mean.

**Comment by felixlinker** [comment]
Closing in favor of EDCD/coriolis/issues/702
